apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yf5ia1qcr-go 
  janus-idp.io/tekton: yf5ia1qcr-go
  backstage.io/kubernetes-id: yf5ia1qcr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yf5ia1qcr-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml